---
title: "REACH MAp"
author: "Sebastian Di Geronimo"
date: 2025-10-13
format: html
editor: source
---

# 1.0 ---- Summary of Document ----



# 2.0 ---- Setup ----


## 2.1 Load Libraries

```{r setup, include=FALSE}
if (!nzchar(system.file(package = "librarian"))) 
  install.packages("librarian")

librarian::shelf(
  quiet = TRUE,
  librarian, conflicted, ggplot2, tibble, tidyr, readr, purrr, dplyr, stringr,
  forcats, lubridate, glue, fs, magrittr, here,
  
  # additional
  readxl, janitor, hms,
  OpenStreetMap, leaflet,
  rerddap,
  sf, metR
)

conflicts_prefer(
  dplyr::filter(), 
  dplyr::select()
  )
```


## 2.2 Load Dataset

```{r load-data}
dir_path <- 
  here() %>%
  rstudioapi::selectDirectory()

sheet_names <- 
  dir_path %>%
  dir_ls(regexp = "(?i)schedule")  %>%
  str_subset("~", negate = TRUE) %>%
  readxl::excel_sheets() %T>% 
  print()

loc_dat <- 
  dir_path %>%
  dir_ls(regexp = "(?i)schedule") %>%
  str_subset("~", negate = TRUE) %>% 
  read_xlsx(.name_repair = make_clean_names, sheet = sheet_names[2]) %>%
  remove_empty("cols") %>%
  drop_na(latitude_decimal_degree, longitude_decimal_degree) %T>%
  print() %>%
  select(waypoint, description, 
         "lat" = latitude_decimal_degree, "long" = longitude_decimal_degree, 
         depth_m, departure_date_time_local
         ) %>%
  mutate(
    long = -long,
    date = as_date(departure_date_time_local),
    description = if_else(str_detect(description, "0"), "CTD/Net Trawl", description)
    ) %T>% 
  print()


# extract date range
invisible(readline("\nDid you update the dates in the loghsheet for the title?\n\n"))
date_string <- 
  dir_path %>%
  dir_ls(regexp = "(?i)logsheet") %>%
  str_subset("(?i)~|aquatic", negate = TRUE) %>%
  {
    sheet_names_log <- excel_sheets(.)
    read_excel(.,
    sheet        = sheet_names_log[str_detect(sheet_names_log, "(?i)info")],
    .name_repair = janitor::make_clean_names
    )
  } %>%
  filter(str_detect(x, "Start|End")) %$%
  as.numeric(x_2) %>%
  excel_numeric_to_date() %>%
  format("%B %d, %Y") %>%
  str_c(collapse = " - ")

date_string <- 
  glue("{basename(dir_path)} ({date_string})") %T>% 
  print()

# set location to save data and plots
dir_plt_save  <- here("data", "plots", "reach_map")
```

## 2.3 Load Rice's Whale Distrbution Shapefile
Shapefile of Rice's Whale Distrbution from:
<https://www.fisheries.noaa.gov/resource/map/rices-whale-core-distribution-area-map-gis-data>
```{r load-data}
# shapefile path
whale_shp_path <- 
  here("data", "raw") %>%
  dir_ls(regexp = "Rices_whale") %>%
  dir_ls(regexp = "shp$")

# load whale distrbution shapefile
whale_shp <- st_read(whale_shp_path)
```

# 3.0 Plot using `leaflet`

Overall points

```{r leaflet}
leaflet::leaflet() %>%
  addTiles() %>%
  addMarkers(loc_dat$long, loc_dat$lat)
```

```{r}
source(here("scripts", "map_files_dwnlod.R"))

# add boundaries for openstreemap
adj_deg <- 1.5 # degree widen
bounds <- 
  c(
    range(loc_dat$long) + c(-adj_deg, adj_deg),
    range(loc_dat$lat) + c(-adj_deg, adj_deg - 0.8)
  ) %T>%
  print()

Sys.setenv(RERDDAP_DEFAULT_URL = "https://coastwatch.pfeg.noaa.gov/erddap/")

world_download(
  path_land = NULL,
  path_topo = here("data", "map_shp", "reach"),
  extent = bounds,
  etopo_version = "ETOPO_2022_v1_15s"
)
Sys.unsetenv("RERDDAP_DEFAULT_URL")

bathy <- 
  here("data", "map_shp", "reach") %>%
  dir_ls()  %>%
  terra::rast() %>%
  as.data.frame(xy = TRUE)


  
# ---- contour function ---- #
contour_labels <- function(
    contour, 
    z_name = "z",
    n_per_level = 1, 
    breaks      = c(25, 50, 100, 500, 1000, 2000, 3000),
    upper_lower = "upper"
    # quantiles   = 0.2,
    # slice_type  = c("max", "random")
    ) {

  if (str_detect(upper_lower, "upper")) {
    upper_lower <- "lower"
  } else if (str_detect(upper_lower, "lower")) {
    upper_lower <- "upper"
    
  } else if (str_detect(upper_lower, "both")) {
    upper_lower <- ".*"
  } 
  
  z <-  matrix(-rev(contour[[z_name]]), nrow = length(unique(contour$x)), byrow = FALSE)
  
  # 1. Extract contours using base R
  clines <- contourLines(
    x = sort(unique(contour$x)),
    y = sort(unique(contour$y)),
    z = z[length(unique(contour$x)):1,],
    levels = breaks
  )
  
  # 2. Find the longest segment for each level
  contour_df <- do.call(
    rbind,
    lapply(clines, function(cl) {
      data.frame(
        level = cl$level,
        x = cl$x,
        y = cl$y,
        length = length(cl$x)
      )
    })
  )
  
  label_pts <-
    contour_df %>%
    mutate(
      mid = if_else(x > mean(range(x)), "upper", "lower")
    ) %>%
    filter(str_detect(mid, upper_lower)) %>%
    slice_sample(n = n_per_level, by = c(level))
  
    return(label_pts)
  # ---- end of function contour_labels ---- #
  }  
  
  
  
bathy_contour_label <- contour_labels(bathy, upper_lower = "upper", n_per_level = 1)

```

```{r}
long_lat_lag <- 
  loc_dat %>%
  mutate(
    lon_lag = dplyr::lead(long, default = first(long)),
    lat_lag = dplyr::lead(lat, default = first(lat)),
    ) %>%
  mutate(
    .by = waypoint,
    te = row_number(),
    t2 = n(),
    waypoint = if_else(row_number() > 1, "", waypoint)
  ) %>%
  select(-te, -t2) %T>% 
  print()
```

# 4.0 Plt using `OpenStreeMap`

Inspired from: <https://ajsmit.github.io/Intro_R_Official/mapping-google.html>

```{r mangrove-stations}
# add boundaries for openstreemap
bounds <- c(-88.5, -82, 26.5, 30.6)

# extract openstreemap tiles
osm_map <-
  openmap(
    bounds[c(4, 1)], # upperleft
    bounds[c(3, 2)], # loweright
    zoom = 8,
    # type = "esri-topo", 
    type = "esri-physical", 
    mergeTiles = TRUE
  ) %>%
  openproj()

# OpenStreetMap::autoplot.OpenStreetMap(osm_map)
  
(loc_map <-
  # plot openstreemap
  OpenStreetMap::autoplot.OpenStreetMap(osm_map) +
    
  # contour lines
  metR::geom_contour2(
    data = bathy,
    aes(
      x = x,
      y = y,
      z = -z
    ),
    col = "grey90",
    breaks = c(3000, 2000, 1000, 500, 100, 50, 25)
  ) +
    
  # whale habitat polygon
  geom_sf(
    data        = whale_shp,
    color       = "grey40",
    fill        = prismatic::clr_lighten("grey40"),
    linewidth   = 0.75,
    alpha       = 0.5,
    linetype    = "dashed",
    inherit.aes = FALSE
  ) +
  shadowtext::geom_shadowtext(
    data = bathy_contour_label,
    aes(x, y, label = level),
    size      = 3,
    bg.colour = "gray30",
    colour    = "white",
    alpha     = 0.7
  ))
```


```{r plt-stations}
shp_label_dict <- 
  c(
  "Arrive" = 21,
  "Waypoint" = 21,
  "CTD/Bongo and Tucker" = 22,
  "CTD/Bongo and Tucker/Subsurface" = 22,
  "CTD" = 24,
  "Surface Buoy/CTD" = 25
)

scale_key <- 
  tribble(
                           ~label, ~shape,       ~fill,  ~color,
                         "Arrive",     21,     "black", "black",
                       "Waypoint",     21,     "black", "black",
                            "CTD",     24, "lightblue", "black",
                      "CTD/Bongo",     21,      "#546", "black",
"CTD/Bongo and Tucker/Subsurface",     22,      "#ffd", "black",
           "CTD/Bongo and Tucker",     22,      "#ffd", "black",
               "CTD/Bongo/Tucker",     22,      "#ffd", "black",
                     "CTD/Tucker",     22,      "#778", "black",
                          "Bongo",     22,      "#434", "black",
                   "Bongo/Tucker",     22,    "yellow", "black",
                         "Tucker",     22,     "green", "black",
               "Surface Buoy/CTD",     25,      "blue", "black",
                         "Missed",      4,       "red",   "red"
  )

loc_map_pts <-
  loc_map +

  # add arrows for cruise track
  ggarchery::geom_arrowsegment(
    data = long_lat_lag,
    aes(
      x     = long,
      xend  = lon_lag,
      y     = lat,
      yend  = lat_lag,
      color = fct_reorder(format(date, "%B %d"), date)
    ),
    # color = "green",
    arrow_positions = 0.5,
    arrows = arrow(length = unit(0.1, "inches")),
    na.rm = TRUE,
    key_glyph = draw_key_point
    # show.legend = FALSE
  ) +

  # add station points
  geom_point(
    data = loc_dat,
    aes(
      x     = long, 
      y     = lat, 
      fill  = fct_reorder(format(date, "%B %d"), date), 
      shape = description
      ),
    size = 3
  ) +

  # add station labels
  ggrepel::geom_text_repel(
    data = distinct(long_lat_lag, waypoint, lat, long),
    aes(x = long, y = lat, label = waypoint),
    max.overlaps       = 15,
    min.segment.length = 0.0,
    size               = 3.5,
    # uncomment for bold letters
    fontface      = "bold",
    color         = "white",
    bg.color      = "black",
    bg.r          = 0.15,
    segment.color = "black",
    # direction     = "x"
  ) +
  labs(
    title = date_string,
    x     = NULL, # "Longitude (°)",
    y     = NULL, # "Latitude (°)",
    color = NULL,
    shape = NULL
  ) +
  # scale_shape_manual(values = shp_label_dict) +
  scale_shape_manual(values = setNames(scale_key$shape, scale_key$label)) +
  coord_sf(expand = FALSE, xlim = bounds[1:2], ylim = bounds[3:4]) +
  guides(
    color = guide_legend(
      keywidth     = 0.05,
      keyheight    = 0.05,
      default.unit = "inch"
    ),
    shape = guide_legend(position = "bottom", nrow = 1),
    fill = "none"
  ) +
  theme_bw() +
  theme(
    legend.position        = "inside",
    legend.position.inside = c(0.91, 0.8),
    legend.text            = element_text(size = 7)
  )
```


```{r show-stations}
loc_map_pts
```

```{r}
loc_dat$description %>%
  unique()
```


```{r}
# set location and name to save plot
plt_save <- here(
  "data", "cam_test", "reach_map", 
  paste0(basename(dir_path), "_pre_cruise_map.jpeg")
  ) %T>% 
  print()

if (FALSE) {
  ggplot2::ggsave(
    filename = plt_save,
    plot = loc_map_pts,
    device   = "jpeg",
    dpi      = 600,
    width    = 11,
    height   = 8.5,
    units    = "in",
    bg       = "white"
  )
} else {
  message("Not saving post cruise map!")
}
```

# 5.0 Save Plots using `camcorder`

After running, will need to redisplay plots for it to

```{r camcorder}
# shelf(camcorder)
# camcorder::gg_record(
#   dir    = here::here("data", "cam_test", "reach_map"),
#   device = "png",
#   dpi    = 600,
#   width = 11,
#   height = 8.5,
#   units  = "in",
#   bg     = "white"
# )
# 
# shell.exec(here::here("data", "cam_test", "reach_map"))
# 
# # uncomment if need to resize
# # camcorder::gg_resize_film(width = 90, height = 90 * 0.5625,  dpi = 600, units = "mm")
# 
```

## 5.1 When done saving plots

```{r stop-camcorder}
# camcorder::gg_stop_recording()
```


```{r}
bathy2 <- 
  here("data", "map_shp", "reach") %>%
  dir_ls()  %>%
  terra::rast() %>%
  as.data.frame(xy = TRUE)

# 1. Extract contours using base R
clines <- contourLines(
  x = sort(unique(bathy2$x)),
  y = sort(unique(bathy2$y)),
  z = matrix(-rev(bathy2$z), nrow = length(unique(bathy2$x)), byrow = FALSE)[length(unique(bathy2$x)):1,],
  levels = c(25, 50, 100, 500, 1000, 2000, 3000)
)

# 2. Find the longest segment for each level
contour_df <- do.call(
  rbind,
  lapply(clines, function(cl) {
    data.frame(
      level = cl$level,
      x = cl$x,
      y = cl$y,
      length = length(cl$x)
    )
  })
)
unique(contour_df$level)

longest <- 
  contour_df %>%
  # group_by(level) %>%
  summarise(
    .by = level,
    # Use the segment with the most points (or your preferred metric)
    idx = which.max(length)
  )
distinct(contour_df, length)

# 3. Label only these segments
# (Alternatively, you may need to join or filter your original 'bathy' or contour data for plotting)

# 4. In your ggplot: use metR geom_label_contour/data for those only (omitting many details since
# extra wrangling is needed).
label_points <- bathy_contour_label <- contour_df %>%
  group_by(level) %>%
  summarise(
    x_label = mean(x),  # or x[middle point]
    y_label = mean(y)
  )

bathy_contour_label2 <-
  contour_df %>%
  mutate(
    mid = if_else(x > mean(range(x)), "upper", "lower")
  ) %>%
  filter(str_detect(mid, "lower")) %>%
  slice_sample(n = 1, by = c(level, mid))

# ---- contour function ---- #
contour_labels <- function(
    contour, 
    z_name = "z",
    n_per_level = 1, 
    breaks      = c(25, 50, 100, 500, 1000, 2000, 3000),
    upper_lower = "upper"
    # quantiles   = 0.2,
    # slice_type  = c("max", "random")
    ) {

  if (str_detect(upper_lower, "upper")) {
    upper_lower <- "lower"
  } else if (str_detect(upper_lower, "lower")) {
    upper_lower <- "upper"
    
  } else if (str_detect(upper_lower, "both")) {
    upper_lower <- ".*"
  } 
  
  z <-  matrix(-rev(contour[[z_name]]), nrow = length(unique(contour$x)), byrow = FALSE)
  
  # 1. Extract contours using base R
  clines <- contourLines(
    x = sort(unique(contour$x)),
    y = sort(unique(contour$y)),
    z = z[length(unique(contour$x)):1,],
    levels = breaks
  )
  
  # 2. Find the longest segment for each level
  contour_df <- do.call(
    rbind,
    lapply(clines, function(cl) {
      data.frame(
        level = cl$level,
        x = cl$x,
        y = cl$y,
        length = length(cl$x)
      )
    })
  )
  
  label_pts <-
    contour_df %>%
    mutate(
      mid = if_else(x > mean(range(x)), "upper", "lower")
    ) %>%
    filter(str_detect(mid, upper_lower)) %>%
    slice_sample(n = n_per_level, by = c(level))
  
    return(label_pts)
  # ---- end of function contour_labels ---- #
  }


bathy_contour_label3 <- contour_labels(bathy2, upper_lower = "both", n_per_level = 1)

ggplot() +
  # contour lines
  metR::geom_contour2(
    data = bathy2,
    aes(
      x = x,
      y = y,
      z = -z
    ),
    col = "blue",
    breaks = c(3000, 2000, 1000, 500, 100, 50, 25)
  ) +
    shadowtext::geom_shadowtext(
    data = bathy_contour_label3,
    # aes(x_label, y_label, label = level),
    aes(x, y, label = level),
    size      = rel(3),
    bg.colour = "gray30",
    colour    = "white",
    alpha     = 0.7
  ) +
  theme()
  

```


```{r}
contour_labels <- function(
    contour, 
    z_name = "z",
    n_per_level = 2, 
    breaks      = c(3000, 2000, 1000, 500, 100, 50, 25), 
    quantiles   = 0.2,
    slice_type  = c("max", "random")
    ) {
  
  library(isoband)
  
  z <- matrix(-contour[[z_name]], nrow = length(unique(contour$y)), byrow = TRUE)
  
  # list of contours breaks with id, x, y as sub-list
  iso <- isolines(
    x = sort(unique(contour$x)),
    y = sort(unique(contour$y)),
    z = z[length(unique(contour$y)):1, ],
    levels = breaks
  )
  # combine iso list of for each contour break keeping contour level
  contours_df <-
    imap(
      iso,
      \(.x, .y) {
        as_tibble(.x) %>%
          mutate(.before = 1, level = .y)
      }
    ) %>%
    list_c()
  # calculate the distances between segments of same ID
  contours_df <-
    contours_df %>%
    arrange(level, id, row_number()) %>%
    mutate(
      .by       = c(level, id),
      dx        = dplyr::lag(x, default = first(x)),
      dy        = dplyr::lag(y, default = first(y)),
      seg_len   = geosphere::distHaversine(cbind(x, y), cbind(dx, dy)) / 1000,
      seg_cum   = cumsum(seg_len),
      seg_total = max(seg_cum)
    )

  label_pts <-
    contours_df %>%
    # drop segments less than x% by level
    filter(seg_total >= quantile(seg_total, quantiles, na.rm = TRUE), .by = level) %>%
    summarise(
      .by = c(level, id),
      # choose mid-point along this segment
      target = max(seg_cum) / 2,
      seg_total = max(seg_cum),
      idx = which.min(abs(seg_cum - target)),
      x = x[idx],
      y = y[idx],
    )
  
  # at most n_per_level
  if (slice_type == "max") {
    label_pts <- 
      label_pts %>%
      slice_max(order_by = seg_total, n = n_per_level, with_ties = FALSE, by = level)
  } else if (slice_type == "min") {
    label_pts <- 
      label_pts %>%
      slice_min(order_by = seg_total, n = n_per_level, with_ties = FALSE, by = level)
  } else if (slice_type == "random") {
    label_pts <- 
      label_pts %>%
        slice_sample(n = 1, by = level)
  } else {
    warning(
      paste0(
        "Pick slice_type:\n", 
        "- max = select top lengths\n", 
        "- random = select 2 random\n",
        "Currently, not reducing labels by n_per_level"
        )
      )
  }

  return(label_pts)
  # ---- end of function contour_labels ---- #
}
```

